version: '3.4'

services:
  nordicdoor:
    image: nordicdoor:dev
    container_name: NordicDoor
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NordicDoor"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/ThomasTvedten/Documents/nordicdoor/nordicdoor/NordicDoor/NordicDoor:/app
      - /Users/ThomasTvedten/Documents/nordicdoor/nordicdoor/NordicDoor:/src
      - /Users/ThomasTvedten/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/ThomasTvedten/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/NordicDoor.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true